// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBspnjJU-3FJz9QSpPjasdTiaN-HJh2RB0',
    appId: '1:761773474835:web:6c34a96d3cbcbee2c86be6',
    messagingSenderId: '761773474835',
    projectId: 'afro-app-d1504',
    authDomain: 'afro-app-d1504.firebaseapp.com',
    storageBucket: 'afro-app-d1504.firebasestorage.app',
    measurementId: 'G-VB9ZGQV4XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByLI02JD9QMNgTjmMViYzCxie-aIxfII8',
    appId: '1:761773474835:android:83a3f2f4ee3560c3c86be6',
    messagingSenderId: '761773474835',
    projectId: 'afro-app-d1504',
    storageBucket: 'afro-app-d1504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJSDhBDY4rsVUXaXN2JBcKo81stfXdMcE',
    appId: '1:761773474835:ios:8879cb4af1a01843c86be6',
    messagingSenderId: '761773474835',
    projectId: 'afro-app-d1504',
    storageBucket: 'afro-app-d1504.firebasestorage.app',
    iosBundleId: 'com.example.afroCaribbeanNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJSDhBDY4rsVUXaXN2JBcKo81stfXdMcE',
    appId: '1:761773474835:ios:8879cb4af1a01843c86be6',
    messagingSenderId: '761773474835',
    projectId: 'afro-app-d1504',
    storageBucket: 'afro-app-d1504.firebasestorage.app',
    iosBundleId: 'com.example.afroCaribbeanNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBspnjJU-3FJz9QSpPjasdTiaN-HJh2RB0',
    appId: '1:761773474835:web:4c61b335b232e5f3c86be6',
    messagingSenderId: '761773474835',
    projectId: 'afro-app-d1504',
    authDomain: 'afro-app-d1504.firebaseapp.com',
    storageBucket: 'afro-app-d1504.firebasestorage.app',
    measurementId: 'G-XSRGYXLKE9',
  );
}
